# theme: jekyll-theme-minimal
remote_theme: "dracula/gh-pages"
exclude:
  - "README.md"
title: Neil's Blog
description: |
  Just something to tinker with
# Additionally, you may choose to set the following optional variables:

# show_downloads: ["true" or "false" to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]
# show_header: ["true" or "false" to indicate whether to show the top header]

# There are also currently the following optional page variables:




# These go on the pages
# icon: [path to file including extension]
# colorspace: [primary page color cyan/green/orange/pink/purple/red/yellow]
